
import __ASTRO_IMAGE_IMPORT_Zy2Hn from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmigration-guide-from-svn-to-git.mdx";
import __ASTRO_IMAGE_IMPORT_1eKaxf from "../../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjavascript%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZhiQGK from "../../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjavascript%2F1-js-runtime.mdx";
import __ASTRO_IMAGE_IMPORT_1rGoX0 from "../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsad-servers%2Fthe-command-line-murders.mdx";
import __ASTRO_IMAGE_IMPORT_ZAGSne from "../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-development%2Fcss-introduction.mdx";
import __ASTRO_IMAGE_IMPORT_108vVa from "../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-development%2Fhtml-introduction.mdx";
import __ASTRO_IMAGE_IMPORT_CvbU6 from "../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-development%2Fcss-layout-introduction.mdx";
import __ASTRO_IMAGE_IMPORT_1EP3Tq from "../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fpages%2Fdisclaimer.md";
import __ASTRO_IMAGE_IMPORT_1EzotV from "../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fpages%2Fabout.md";
import __ASTRO_IMAGE_IMPORT_Z550wz from "../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fpages%2Fplayground.mdx";
import __ASTRO_IMAGE_IMPORT_Z13XqiB from "../../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-development%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1U0WOW from "../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-development%2Fjs-introduction.mdx";
import __ASTRO_IMAGE_IMPORT_ZWmj58 from "../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvod-simulate-live-hls%2Findex.mdx";
export default new Map([["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmigration-guide-from-svn-to-git.mdx", __ASTRO_IMAGE_IMPORT_Zy2Hn], ["../../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjavascript%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1eKaxf], ["../../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjavascript%2F1-js-runtime.mdx", __ASTRO_IMAGE_IMPORT_ZhiQGK], ["../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsad-servers%2Fthe-command-line-murders.mdx", __ASTRO_IMAGE_IMPORT_1rGoX0], ["../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-development%2Fcss-introduction.mdx", __ASTRO_IMAGE_IMPORT_ZAGSne], ["../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-development%2Fhtml-introduction.mdx", __ASTRO_IMAGE_IMPORT_108vVa], ["../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-development%2Fcss-layout-introduction.mdx", __ASTRO_IMAGE_IMPORT_CvbU6], ["../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fpages%2Fdisclaimer.md", __ASTRO_IMAGE_IMPORT_1EP3Tq], ["../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fpages%2Fabout.md", __ASTRO_IMAGE_IMPORT_1EzotV], ["../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fpages%2Fplayground.mdx", __ASTRO_IMAGE_IMPORT_Z550wz], ["../../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-development%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z13XqiB], ["../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-development%2Fjs-introduction.mdx", __ASTRO_IMAGE_IMPORT_Z1U0WOW], ["../../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvod-simulate-live-hls%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZWmj58]]);
		