
export default new Map([
["src/content/blog/migration-guide-from-svn-to-git.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fmigration-guide-from-svn-to-git.mdx&astroContentModuleFlag=true")],
["src/content/blog/javascript/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fjavascript%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/javascript/1-js-runtime.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fjavascript%2F1-js-runtime.mdx&astroContentModuleFlag=true")],
["src/content/blog/sad-servers/the-command-line-murders.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fsad-servers%2Fthe-command-line-murders.mdx&astroContentModuleFlag=true")],
["src/content/blog/web-development/css-introduction.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fweb-development%2Fcss-introduction.mdx&astroContentModuleFlag=true")],
["src/content/blog/web-development/html-introduction.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fweb-development%2Fhtml-introduction.mdx&astroContentModuleFlag=true")],
["src/content/blog/web-development/css-layout-introduction.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fweb-development%2Fcss-layout-introduction.mdx&astroContentModuleFlag=true")],
["src/pages/playground.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fpages%2Fplayground.mdx&astroContentModuleFlag=true")],
["src/content/blog/web-development/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fweb-development%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/web-development/js-introduction.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fweb-development%2Fjs-introduction.mdx&astroContentModuleFlag=true")],
["src/content/blog/vod-simulate-live-hls/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fvod-simulate-live-hls%2Findex.mdx&astroContentModuleFlag=true")]]);
		